In [3]:
import pandas as pd
import seaborn as sns
import matplotlib as plt

In [4]:
hit = pd.read_csv("2023hitterstats.csv")

In [8]:
#remove pitchers from the list

def remove_pitchers(hit):
    filtered_hit = hit[hit['Pos Summary'] != '1']
    filtered_hit.reset_index(drop=True,inplace=True)
    filtered_hit['Rk'] = filtered_hit.index +1
    return filtered_hit

hit = remove_pitchers(hit)

C:\Users\chris\AppData\Local\Temp\ipykernel_15832\990155713.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_hit['Rk'] = filtered_hit.index +1

In [9]:
hit

,Rk,Name,Age,Tm,Lg,G,PA,AB,R,H,...,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,Pos Summary
0,1,CJ Abrams,22,WSN,NL,151,614,563,83,138,...,0.412,0.712,97.0,232,7,13,3,3,2,*6/H
1,2,José Abreu,36,HOU,AL,141,594,540,62,128,...,0.383,0.680,87.0,207,16,6,0,6,1,*3/D
2,3,Wilyer Abreu,24,BOS,AL,28,85,76,10,24,...,0.474,0.862,132.0,36,0,0,0,0,0,87/H9D
3,4,Ronald Acuña Jr.,25,ATL,NL,159,735,643,149,217,...,0.596,1.012,169.0,383,15,9,0,3,3,*9/D
4,5,Willy Adames,27,MIL,NL,149,638,553,73,120,...,0.407,0.717,93.0,225,12,6,0,6,1,*6/D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,772,Jared Young,27,CHC,NL,16,47,43,8,8,...,0.465,0.720,91.0,20,1,1,0,0,0,3/DH
772,773,Seby Zavala,29,TOT,MLB,73,193,175,17,30,...,0.314,0.545,48.0,55,4,2,2,2,0,2/H1
773,774,Seby Zavala,29,CHW,AL,66,176,161,15,25,...,0.304,0.511,39.0,49,4,1,2,2,0,2/H
774,775,Seby Zavala,29,ARI,NL,7,17,14,2,5,...,0.429,0.899,151.0,6,0,1,0,0,0,/21H
775,776,Mike Zunino,32,CLE,AL,42,140,124,11,22,...,0.306,0.578,61.0,38,3,1,0,0,0,2